# Generated by Django 4.1.7 on 2023-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="包裹编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="包裹名称")),
                ("photo", models.URLField(blank=True, verbose_name="外观")),
                ("large", models.BooleanField(default=False, verbose_name="大件")),
                ("send_time", models.DateTimeField(blank=True, verbose_name="发货时间")),
                ("receive_time", models.DateTimeField(blank=True, verbose_name="收货时间")),
            ],
        ),
    ]
