# Generated by Django 4.1.7 on 2023-05-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("express", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="package",
            name="addressee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="addressee",
                to="user.userinfo",
                verbose_name="收件人",
            ),
        ),
        migrations.AddField(
            model_name="package",
            name="addresser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="addresser",
                to="user.userinfo",
                verbose_name="发件人",
            ),
        ),
    ]
