# Generated by Django 4.1.7 on 2023-05-02 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
        ("vehicle", "0001_initial"),
        ("route", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="route",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_of_route",
                to="vehicle.vehicle",
                verbose_name="车辆信息",
            ),
        ),
        migrations.AddField(
            model_name="deliveraddress",
            name="raiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="address_raiser",
                to="user.userinfo",
                verbose_name="地址创建人",
            ),
        ),
    ]
