# Generated by Django 4.1.7 on 2023-05-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="运营公司编号"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="运营公司名称")),
                (
                    "abbreviation",
                    models.CharField(blank=True, max_length=50, verbose_name="运营公司简称"),
                ),
            ],
        ),
    ]
