# Generated by Django 4.1.7 on 2023-05-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="运营公司编号"
            ),
        ),
    ]
